/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import Login.Login;
import Kasir_Produk.Menu;
import java.awt.BorderLayout;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author achmad ifan
 */
public class Kasir extends javax.swing.JFrame {

    /**
     * Creates new form Kasir
     */
    
    public void Jam(){
    DateTimeFormatter ff = DateTimeFormatter.ofPattern("HH:mm:ss ");
    String ft = LocalDateTime.now().format(ff);
    
    
    }
    
    
    
    public void bottunrounded (int atas, int bawah){
        roundedatas.setLocation(226, atas);
        roundedbawah.setLocation(226, bawah);
        dalambawah.setRoundedkananatas(22);
        dalamatas.setRoundedkananbawah(22);
        roundedatas.setVisible(true);
        roundedbawah.setVisible(true);
        
    }
    
    
    public Kasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundednew1 = new Aset.roundednew();
        jLabel1 = new javax.swing.JLabel();
        Frame1 = new Aset.roundednew();
        MStok = new Aset.button();
        MProduk = new Aset.button();
        MRegis = new Aset.button();
        MLaporan = new Aset.button();
        MLogout = new Aset.button();
        roundedbawah = new Aset.roundednew();
        dalambawah = new Aset.roundednew();
        roundedatas = new Aset.roundednew();
        dalamatas = new Aset.roundednew();
        roundednew2 = new Aset.roundednew();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        roundednew1.setColorend(new java.awt.Color(146, 199, 207));
        roundednew1.setColorstar(new java.awt.Color(134, 211, 222));
        roundednew1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Group 101 (3).png"))); // NOI18N
        roundednew1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 34, -1, -1));

        Frame1.setColorend(new java.awt.Color(238, 238, 238));
        Frame1.setColorstar(new java.awt.Color(238, 238, 238));
        Frame1.setRoundedkananatas(94);
        Frame1.setRoundedkananbawah(94);
        Frame1.setRoundedkiriatas(94);
        Frame1.setRoundedkiribawah(94);

        javax.swing.GroupLayout Frame1Layout = new javax.swing.GroupLayout(Frame1);
        Frame1.setLayout(Frame1Layout);
        Frame1Layout.setHorizontalGroup(
            Frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        Frame1Layout.setVerticalGroup(
            Frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        roundednew1.add(Frame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 40, 1210, 770));

        MStok.setForeground(new java.awt.Color(90, 142, 149));
        MStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/MStok.png"))); // NOI18N
        MStok.setText("Transaksi");
        MStok.setColor(new java.awt.Color(238, 238, 238));
        MStok.setColorborder(new java.awt.Color(238, 238, 238));
        MStok.setColorclic(new java.awt.Color(238, 238, 238));
        MStok.setColorover(new java.awt.Color(238, 238, 238));
        MStok.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        MStok.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MStok.setIconTextGap(30);
        MStok.setRadius(44);
        MStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MStokActionPerformed(evt);
            }
        });
        roundednew1.add(MStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 380, 224, 60));

        MProduk.setForeground(new java.awt.Color(90, 142, 149));
        MProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/MProduk.png"))); // NOI18N
        MProduk.setText("Produk");
        MProduk.setColor(new java.awt.Color(238, 238, 238));
        MProduk.setColorborder(new java.awt.Color(238, 238, 238));
        MProduk.setColorclic(new java.awt.Color(238, 238, 238));
        MProduk.setColorover(new java.awt.Color(238, 238, 238));
        MProduk.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        MProduk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MProduk.setIconTextGap(30);
        MProduk.setRadius(44);
        MProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MProdukActionPerformed(evt);
            }
        });
        roundednew1.add(MProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 300, 224, 60));

        MRegis.setForeground(new java.awt.Color(90, 142, 149));
        MRegis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/MRegis.png"))); // NOI18N
        MRegis.setText("Check Out");
        MRegis.setColor(new java.awt.Color(238, 238, 238));
        MRegis.setColorborder(new java.awt.Color(238, 238, 238));
        MRegis.setColorclic(new java.awt.Color(238, 238, 238));
        MRegis.setColorover(new java.awt.Color(238, 238, 238));
        MRegis.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        MRegis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MRegis.setIconTextGap(30);
        MRegis.setRadius(44);
        MRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRegisActionPerformed(evt);
            }
        });
        roundednew1.add(MRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 540, 224, 60));

        MLaporan.setForeground(new java.awt.Color(90, 142, 149));
        MLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/MLaporan.png"))); // NOI18N
        MLaporan.setText("Status");
        MLaporan.setColor(new java.awt.Color(238, 238, 238));
        MLaporan.setColorborder(new java.awt.Color(238, 238, 238));
        MLaporan.setColorclic(new java.awt.Color(238, 238, 238));
        MLaporan.setColorover(new java.awt.Color(238, 238, 238));
        MLaporan.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        MLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MLaporan.setIconTextGap(30);
        MLaporan.setRadius(44);
        MLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MLaporanActionPerformed(evt);
            }
        });
        roundednew1.add(MLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 460, 224, 60));

        MLogout.setForeground(new java.awt.Color(90, 142, 149));
        MLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/MLogout.png"))); // NOI18N
        MLogout.setText("Log Out");
        MLogout.setToolTipText("");
        MLogout.setColor(new java.awt.Color(238, 238, 238));
        MLogout.setColorborder(new java.awt.Color(238, 238, 238));
        MLogout.setColorclic(new java.awt.Color(238, 238, 238));
        MLogout.setColorover(new java.awt.Color(238, 238, 238));
        MLogout.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        MLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MLogout.setIconTextGap(30);
        MLogout.setRadius(44);
        MLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MLogoutActionPerformed(evt);
            }
        });
        roundednew1.add(MLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 620, 224, 60));

        roundedbawah.setColorend(new java.awt.Color(238, 238, 238));
        roundedbawah.setColorstar(new java.awt.Color(238, 238, 238));

        dalambawah.setColorend(new java.awt.Color(134, 211, 222));
        dalambawah.setColorstar(new java.awt.Color(134, 211, 222));
        dalambawah.setRoundedkananatas(22);

        javax.swing.GroupLayout dalambawahLayout = new javax.swing.GroupLayout(dalambawah);
        dalambawah.setLayout(dalambawahLayout);
        dalambawahLayout.setHorizontalGroup(
            dalambawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        dalambawahLayout.setVerticalGroup(
            dalambawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout roundedbawahLayout = new javax.swing.GroupLayout(roundedbawah);
        roundedbawah.setLayout(roundedbawahLayout);
        roundedbawahLayout.setHorizontalGroup(
            roundedbawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dalambawah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roundedbawahLayout.setVerticalGroup(
            roundedbawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedbawahLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dalambawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundednew1.add(roundedbawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 360, 40, 22));

        roundedatas.setColorend(new java.awt.Color(238, 238, 238));
        roundedatas.setColorstar(new java.awt.Color(238, 238, 238));

        dalamatas.setColorend(new java.awt.Color(134, 211, 222));
        dalamatas.setColorstar(new java.awt.Color(134, 211, 222));
        dalamatas.setRoundedkananbawah(22);

        javax.swing.GroupLayout dalamatasLayout = new javax.swing.GroupLayout(dalamatas);
        dalamatas.setLayout(dalamatasLayout);
        dalamatasLayout.setHorizontalGroup(
            dalamatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        dalamatasLayout.setVerticalGroup(
            dalamatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout roundedatasLayout = new javax.swing.GroupLayout(roundedatas);
        roundedatas.setLayout(roundedatasLayout);
        roundedatasLayout.setHorizontalGroup(
            roundedatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dalamatas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roundedatasLayout.setVerticalGroup(
            roundedatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedatasLayout.createSequentialGroup()
                .addComponent(dalamatas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 60, Short.MAX_VALUE))
        );

        roundednew1.add(roundedatas, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 278, 40, 82));

        roundednew2.setColorend(new java.awt.Color(238, 238, 238));
        roundednew2.setColorstar(new java.awt.Color(238, 238, 238));
        roundednew2.setRoundedkananatas(40);
        roundednew2.setRoundedkananbawah(40);
        roundednew2.setRoundedkiriatas(40);
        roundednew2.setRoundedkiribawah(40);
        roundednew2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(90, 142, 149));
        jLabel2.setText("SAK - GB");
        roundednew2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(90, 142, 149));
        jLabel4.setText("SAK - GB");
        roundednew2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, -1));

        roundednew1.add(roundednew2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 220, 120));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("SAK - GB");
        roundednew1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 240, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundednew1, javax.swing.GroupLayout.PREFERRED_SIZE, 1552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundednew1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1552, 889);
    }// </editor-fold>//GEN-END:initComponents

    private void MStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MStokActionPerformed


        bottunrounded(358, 440);

    }//GEN-LAST:event_MStokActionPerformed

    private void MProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MProdukActionPerformed
        Frame1.setLayout(new BorderLayout());
        Frame1.removeAll();
        Frame1.add(new Menu());
        Frame1.revalidate();
        Frame1.repaint();

        //        MProduk.setSize(270, 60);
        //        MStok.setSize(224, 60);
        //        MLaporan.setSize(224, 60);
        //        MRegis.setSize(224, 60);
        //        MLogout.setSize(224, 60);

        bottunrounded(278, 360);

    }//GEN-LAST:event_MProdukActionPerformed

    private void MRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRegisActionPerformed
        //        MRegis.setSize(270, 60);
        //        MProduk.setSize(224, 60);
        //        MLaporan.setSize(224, 60);
        //        MStok.setSize(224, 60);
        //        MLogout.setSize(224, 60);

        bottunrounded(518, 600);

    }//GEN-LAST:event_MRegisActionPerformed

    private void MLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MLaporanActionPerformed
        //        MLaporan.setSize(270, 60);
        //        MProduk.setSize(224, 60);
        //        MStok.setSize(224, 60);
        //        MRegis.setSize(224, 60);
        //        MLogout.setSize(224, 60);

        bottunrounded(438, 520);
    }//GEN-LAST:event_MLaporanActionPerformed

    private void MLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MLogoutActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Aset.roundednew Frame1;
    private Aset.button MLaporan;
    private Aset.button MLogout;
    private Aset.button MProduk;
    private Aset.button MRegis;
    private Aset.button MStok;
    private Aset.roundednew dalamatas;
    private Aset.roundednew dalambawah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private Aset.roundednew roundedatas;
    private Aset.roundednew roundedbawah;
    private Aset.roundednew roundednew1;
    private Aset.roundednew roundednew2;
    // End of variables declaration//GEN-END:variables
}
