/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import Koneksi.Koneksi;
import java.sql.Connection;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author achmad ifan
 */
public class test extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    
    
    public void Login (String Code){
        DateTimeFormatter Waktu = DateTimeFormatter.ofPattern("HH:mm:ss ");
        DateTimeFormatter Jam = DateTimeFormatter.ofPattern("HH");
        String FWaktu = LocalDateTime.now().format(Waktu);
        String FJam = LocalDateTime.now().format(Jam);
        int IJam = Integer.parseInt(FJam);
        // deklarasi bulan, hari, dan tahun
        DateTimeFormatter Tanggal = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        

        // mengubah format ke string
        LocalDateTime now = LocalDateTime.now();
        String fm = now.format(Tanggal); // Mengubah LocalDateTime menjadi string dengan format yyyy-MM-dd
      
        
    
    try {
    String sql = "SELECT * FROM user WHERE rfid = ?";
    java.sql.Connection conn = (Connection) Koneksi.koneksi();
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    
    // Set parameter untuk prepared statement
    pst.setString(1, Code);
//    pst.setString(2, txt_pw.getText());
    
    java.sql.ResultSet rs = pst.executeQuery();
    
    if (rs.next()) {
        JOptionPane.showMessageDialog(null, "berhasil login");
        int choice = JOptionPane.showOptionDialog( null, "Apakah Anda Ingin Melakukan Presensi","Presensi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, null,null);
        if (rs.getString("role").equals("owner")) {
            this.dispose();
            
            
        } else if (rs.getString("role").equals("kasir")) {
            if(IJam<07&& choice == JOptionPane.YES_OPTION){
                try{
                String Presensi = "INSERT INTO `presensi` (`Id_Presensi`, `Tanggal`, `Keter`, `Waktu`) VALUES (NULL, ?, ?, ?)";
                pst = conn.prepareStatement(Presensi);
                pst.setString(1,fm);
                pst.setString(2,"Hadir");
                pst.setString(3,FJam);
                
                pst.executeUpdate();
                }catch(Exception e){
                   System.err.println("Terjadi kesalahan saat memasukkan data pelanggan: " + e.getMessage()); 
                }
                
            }
            
        }
    } else {
        JOptionPane.showMessageDialog(null, "username atau password salah");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}
    }
    public test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Scanner input = new Scanner (System.in);
        
        jLabel1.setText("Tempelkan kartu ");
        String code = input.next();
        
        Login(code);
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
