/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import javax.swing.JOptionPane;
import Koneksi.Koneksi;
import java.sql.*;
/**
 *
 * @author achmad ifan
 */
public class Verifikasi extends javax.swing.JFrame {

    Connection conn = (Connection) Koneksi.koneksi();
    String id_user = "";
    
    /**
     * Creates new form Verifikasi
     */
    
    public void newpass(String id){
//        String pertama = new_pw.getText();
//        String kedua = konfirmasi_pw.getText();
        
        
        if (new_pw.getText().equals(konfirmasi_pw.getText())){
             try {
                String sql = "UPDATE `user` SET `Password`= ? WHERE Id_user = ?";

                java.sql.PreparedStatement pst = conn.prepareStatement(sql);

                // Set parameter untuk prepared statement
                pst.setString(1, new_pw.getText());
                pst.setString(2, id);

                int row = pst.executeUpdate();
                if (row >0) {
                  JOptionPane.showMessageDialog(null, "Verifikasi berhasil");
                  

                } else {
                    JOptionPane.showMessageDialog(null, "username atau makanan favorit salah");
                }
            } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "ga mirip woi!!");
        }
    }
    
     public void Verif (){     
    try {
    String sql = "SELECT * FROM user WHERE Username = ? AND Makanan_favorite = ?";
    
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    
    // Set parameter untuk prepared statement
    pst.setString(1, txt_user.getText());
    pst.setString(2, txt_mf.getText());
    
    java.sql.ResultSet rs = pst.executeQuery();
    if (rs.next()) {
        String id = rs.getString("Id_user");
        id_user = id;
      JOptionPane.showMessageDialog(null, "Verifikasi berhasil"+id_user);
      newpw.setVisible(true);
        
    } else {
        JOptionPane.showMessageDialog(null, "username atau makanan favorit salah");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}
}
   
   
    
    public Verifikasi() {
        initComponents();
        newpw.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundednew2 = new Aset.roundednew();
        jLabel2 = new javax.swing.JLabel();
        button2 = new Aset.button();
        newpw = new Aset.roundednew();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        konfirmasi_pw = new Aset.RoundedTextField();
        new_pw = new Aset.RoundedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        button4 = new Aset.button();
        roundednew1 = new Aset.roundednew();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_mf = new Aset.RoundedTextField();
        txt_user = new Aset.RoundedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        button3 = new Aset.button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundednew2.setColorend(new java.awt.Color(146, 199, 207));
        roundednew2.setColorstar(new java.awt.Color(93, 224, 244));
        roundednew2.setRoundedkananatas(10000);
        roundednew2.setRoundedkananbawah(10000);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Group 101.png"))); // NOI18N

        button2.setForeground(new java.awt.Color(42, 85, 87));
        button2.setText("Login Dengan RFID");
        button2.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        button2.setRadius(20);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundednew2Layout = new javax.swing.GroupLayout(roundednew2);
        roundednew2.setLayout(roundednew2Layout);
        roundednew2Layout.setHorizontalGroup(
            roundednew2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundednew2Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(roundednew2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundednew2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        roundednew2Layout.setVerticalGroup(
            roundednew2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundednew2Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        getContentPane().add(roundednew2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 880));

        newpw.setColorend(new java.awt.Color(170, 215, 217));
        newpw.setColorstar(new java.awt.Color(170, 215, 217));
        newpw.setRoundedkananatas(51);
        newpw.setRoundedkananbawah(51);
        newpw.setRoundedkiriatas(51);
        newpw.setRoundedkiribawah(51);
        newpw.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Password.png"))); // NOI18N
        newpw.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 265, -1, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Password.png"))); // NOI18N
        newpw.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 165, -1, 40));

        jLabel10.setFont(new java.awt.Font("Poppins", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(42, 85, 87));
        jLabel10.setText("PASSWORD BARU");
        newpw.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 50, -1, 39));

        konfirmasi_pw.setForeground(new java.awt.Color(42, 85, 87));
        konfirmasi_pw.setText(" ");
        konfirmasi_pw.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        konfirmasi_pw.setMargin(new java.awt.Insets(5, 45, 2, 6));
        konfirmasi_pw.setRoundedkananatas(20);
        konfirmasi_pw.setRoundedkananbawah(20);
        konfirmasi_pw.setRoundedkiriatas(20);
        konfirmasi_pw.setRoundedkiribawah(20);
        konfirmasi_pw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                konfirmasi_pwMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                konfirmasi_pwMouseExited(evt);
            }
        });
        newpw.add(konfirmasi_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 370, 50));

        new_pw.setForeground(new java.awt.Color(42, 85, 87));
        new_pw.setText("Username");
        new_pw.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        new_pw.setMargin(new java.awt.Insets(5, 45, 2, 6));
        new_pw.setRoundedkananatas(20);
        new_pw.setRoundedkananbawah(20);
        new_pw.setRoundedkiriatas(20);
        new_pw.setRoundedkiribawah(20);
        new_pw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_pwMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                new_pwMouseExited(evt);
            }
        });
        newpw.add(new_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 370, 50));

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(42, 85, 87));
        jLabel11.setText("Konfirmasi Password");
        newpw.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 39));

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(42, 85, 87));
        jLabel12.setText("Password Baru");
        newpw.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 39));

        button4.setBackground(new java.awt.Color(229, 225, 218));
        button4.setForeground(new java.awt.Color(42, 85, 87));
        button4.setText("KONFIRMASI");
        button4.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        button4.setRadius(20);
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        newpw.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 370, 50));

        getContentPane().add(newpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, 449, 470));

        roundednew1.setColorend(new java.awt.Color(170, 215, 217));
        roundednew1.setColorstar(new java.awt.Color(170, 215, 217));
        roundednew1.setRoundedkananatas(51);
        roundednew1.setRoundedkananbawah(51);
        roundednew1.setRoundedkiriatas(51);
        roundednew1.setRoundedkiribawah(51);
        roundednew1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Password.png"))); // NOI18N
        roundednew1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 265, -1, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Username.png"))); // NOI18N
        roundednew1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 165, -1, 40));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(42, 85, 87));
        jLabel3.setText("VERIFIKASI");
        roundednew1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 50, -1, 39));

        txt_mf.setForeground(new java.awt.Color(42, 85, 87));
        txt_mf.setText(" ");
        txt_mf.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        txt_mf.setMargin(new java.awt.Insets(5, 45, 2, 6));
        txt_mf.setRoundedkananatas(20);
        txt_mf.setRoundedkananbawah(20);
        txt_mf.setRoundedkiriatas(20);
        txt_mf.setRoundedkiribawah(20);
        txt_mf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_mfMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_mfMouseExited(evt);
            }
        });
        roundednew1.add(txt_mf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 370, 50));

        txt_user.setForeground(new java.awt.Color(42, 85, 87));
        txt_user.setText("Username");
        txt_user.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        txt_user.setMargin(new java.awt.Insets(5, 45, 2, 6));
        txt_user.setRoundedkananatas(20);
        txt_user.setRoundedkananbawah(20);
        txt_user.setRoundedkiriatas(20);
        txt_user.setRoundedkiribawah(20);
        txt_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_userMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_userMouseExited(evt);
            }
        });
        roundednew1.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 370, 50));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(42, 85, 87));
        jLabel4.setText("Makanan Favorit");
        roundednew1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 39));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(42, 85, 87));
        jLabel5.setText("Username");
        roundednew1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 39));

        button3.setBackground(new java.awt.Color(229, 225, 218));
        button3.setForeground(new java.awt.Color(42, 85, 87));
        button3.setText("KONFIRMASI");
        button3.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        button3.setRadius(20);
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        roundednew1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 370, 50));

        getContentPane().add(roundednew1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, 449, 470));

        setBounds(0, 0, 1552, 889);
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        this.dispose();
        RFID pp = new RFID();
        pp.setVisible(true);
    }//GEN-LAST:event_button2ActionPerformed

    private void txt_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_userMouseClicked
        txt_user.setText(null);

    }//GEN-LAST:event_txt_userMouseClicked

    private void txt_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_userMouseExited
        String i = txt_user.getText();
        if (i.equals("")){
            txt_user.setText("Username");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userMouseExited

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        Verif();
    }//GEN-LAST:event_button3ActionPerformed

    private void txt_mfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_mfMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mfMouseClicked

    private void txt_mfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_mfMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mfMouseExited

    private void konfirmasi_pwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_konfirmasi_pwMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_konfirmasi_pwMouseClicked

    private void konfirmasi_pwMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_konfirmasi_pwMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_konfirmasi_pwMouseExited

    private void new_pwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_pwMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_new_pwMouseClicked

    private void new_pwMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_pwMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_new_pwMouseExited

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        newpass(id_user);
    }//GEN-LAST:event_button4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Verifikasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Aset.button button2;
    private Aset.button button3;
    private Aset.button button4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private Aset.RoundedTextField konfirmasi_pw;
    private Aset.RoundedTextField new_pw;
    private Aset.roundednew newpw;
    private Aset.roundednew roundednew1;
    private Aset.roundednew roundednew2;
    private Aset.RoundedTextField txt_mf;
    private Aset.RoundedTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
