/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Kasir_Produk;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import raven.glasspanepopup.GlassPanePopup;
import Aset.roundednew;

/**
 *
 * @author achmad ifan
 */
public class datadiri extends roundednew {

    /**
     * Creates new form datadiri
     */
    public datadiri() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundednew2 = new Aset.roundednew();
        roundednew1 = new Aset.roundednew();
        judul = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        roundedTextField1 = new Aset.RoundedTextField();
        roundedTextField2 = new Aset.RoundedTextField();
        judul3 = new javax.swing.JLabel();
        roundedTextField3 = new Aset.RoundedTextField();
        button1 = new Aset.button();
        judul4 = new javax.swing.JLabel();

        setColorend(new java.awt.Color(242, 242, 242));
        setColorstar(new java.awt.Color(242, 242, 242));
        setRoundedkananatas(30);
        setRoundedkananbawah(30);
        setRoundedkiriatas(30);
        setRoundedkiribawah(30);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundednew2.setColorend(new java.awt.Color(242, 242, 242));
        roundednew2.setColorstar(new java.awt.Color(242, 242, 242));
        roundednew2.setRoundedkananatas(30);
        roundednew2.setRoundedkananbawah(30);
        roundednew2.setRoundedkiriatas(30);
        roundednew2.setRoundedkiribawah(30);
        roundednew2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundednew1.setColorend(new java.awt.Color(170, 215, 217));
        roundednew1.setColorstar(new java.awt.Color(170, 215, 217));
        roundednew1.setRoundedkananatas(15);
        roundednew1.setRoundedkananbawah(15);
        roundednew1.setRoundedkiriatas(15);
        roundednew1.setRoundedkiribawah(15);

        judul.setFont(new java.awt.Font("Poppins", 1, 30)); // NOI18N
        judul.setForeground(new java.awt.Color(90, 142, 149));
        judul.setText("Tambah Produk");

        judul1.setFont(new java.awt.Font("Poppins", 0, 25)); // NOI18N
        judul1.setForeground(new java.awt.Color(90, 142, 149));
        judul1.setText("Nama");

        judul2.setFont(new java.awt.Font("Poppins", 0, 25)); // NOI18N
        judul2.setForeground(new java.awt.Color(90, 142, 149));
        judul2.setText("Nomer Telepone");

        roundedTextField1.setBackground(new java.awt.Color(251, 249, 241));
        roundedTextField1.setForeground(new java.awt.Color(153, 153, 153));
        roundedTextField1.setText("roundedTextField1");
        roundedTextField1.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        roundedTextField1.setRoundedkananatas(20);
        roundedTextField1.setRoundedkananbawah(20);
        roundedTextField1.setRoundedkiriatas(20);
        roundedTextField1.setRoundedkiribawah(20);

        roundedTextField2.setBackground(new java.awt.Color(251, 249, 241));
        roundedTextField2.setForeground(new java.awt.Color(153, 153, 153));
        roundedTextField2.setText("roundedTextField1");
        roundedTextField2.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        roundedTextField2.setRoundedkananatas(20);
        roundedTextField2.setRoundedkananbawah(20);
        roundedTextField2.setRoundedkiriatas(20);
        roundedTextField2.setRoundedkiribawah(20);

        judul3.setFont(new java.awt.Font("Poppins", 0, 25)); // NOI18N
        judul3.setForeground(new java.awt.Color(90, 142, 149));
        judul3.setText("Nama");

        roundedTextField3.setBackground(new java.awt.Color(251, 249, 241));
        roundedTextField3.setForeground(new java.awt.Color(153, 153, 153));
        roundedTextField3.setText("roundedTextField1");
        roundedTextField3.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        roundedTextField3.setRoundedkananatas(20);
        roundedTextField3.setRoundedkananbawah(20);
        roundedTextField3.setRoundedkiriatas(20);
        roundedTextField3.setRoundedkiribawah(20);

        button1.setForeground(new java.awt.Color(90, 142, 149));
        button1.setText("KONFIRMASI");
        button1.setColor(new java.awt.Color(229, 225, 218));
        button1.setColorborder(new java.awt.Color(229, 225, 218));
        button1.setColorclic(new java.awt.Color(229, 225, 218));
        button1.setColorover(new java.awt.Color(229, 225, 218));
        button1.setFont(new java.awt.Font("Poppins", 1, 25)); // NOI18N
        button1.setRadius(20);

        judul4.setFont(new java.awt.Font("Poppins SemiBold", 0, 30)); // NOI18N
        judul4.setForeground(new java.awt.Color(90, 142, 149));
        judul4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul4.setText("Kembali");

        javax.swing.GroupLayout roundednew1Layout = new javax.swing.GroupLayout(roundednew1);
        roundednew1.setLayout(roundednew1Layout);
        roundednew1Layout.setHorizontalGroup(
            roundednew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundednew1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roundednew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundednew1Layout.createSequentialGroup()
                        .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundednew1Layout.createSequentialGroup()
                        .addGroup(roundednew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(judul4, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roundednew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(roundedTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundednew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(judul3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(roundednew1Layout.createSequentialGroup()
                                        .addGroup(roundednew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(roundedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addGroup(roundednew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(roundedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(46, 46, 46))))
        );
        roundednew1Layout.setVerticalGroup(
            roundednew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundednew1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(roundednew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(roundednew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roundedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(judul3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(roundedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(judul4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        roundednew2.add(roundednew1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 45, 665, 460));

        add(roundednew2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 755, 550));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Aset.button button1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    private javax.swing.JLabel judul4;
    private Aset.RoundedTextField roundedTextField1;
    private Aset.RoundedTextField roundedTextField2;
    private Aset.RoundedTextField roundedTextField3;
    private Aset.roundednew roundednew1;
    private Aset.roundednew roundednew2;
    // End of variables declaration//GEN-END:variables
}
