/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Kasir_Produk;

import Aset.roundednew;

/**
 *
 * @author achmad ifan
 */
public class Menu extends roundednew {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundednew3 = new Aset.roundednew();
        judul = new javax.swing.JLabel();
        txt_harga = new Aset.RoundedTextField();
        jLabel3 = new javax.swing.JLabel();
        button1 = new Aset.button();
        jLabel2 = new javax.swing.JLabel();
        txt_name2 = new Aset.RoundedTextField();
        txt_harga1 = new Aset.RoundedTextField();
        jLabel8 = new javax.swing.JLabel();
        roundednew4 = new Aset.roundednew();
        button2 = new Aset.button();
        Hapus = new Aset.button();
        Update = new Aset.button();
        roundednew5 = new Aset.roundednew();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_name1 = new Aset.RoundedTextField();
        txt_name3 = new Aset.RoundedTextField();
        txt_name4 = new Aset.RoundedTextField();
        txt_name5 = new Aset.RoundedTextField();
        txt_name6 = new Aset.RoundedTextField();

        setBackground(new java.awt.Color(242, 242, 242));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundednew3.setColorend(new java.awt.Color(170, 215, 217));
        roundednew3.setColorstar(new java.awt.Color(170, 215, 217));
        roundednew3.setRoundedkananatas(50);
        roundednew3.setRoundedkananbawah(50);
        roundednew3.setRoundedkiriatas(50);
        roundednew3.setRoundedkiribawah(50);
        roundednew3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul.setFont(new java.awt.Font("Poppins", 1, 30)); // NOI18N
        judul.setForeground(new java.awt.Color(90, 142, 149));
        judul.setText("Tambah Produk");
        roundednew3.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, 31));

        txt_harga.setBackground(new java.awt.Color(242, 242, 242));
        txt_harga.setBorder(null);
        txt_harga.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_harga.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        txt_harga.setRoundedkananatas(15);
        txt_harga.setRoundedkananbawah(15);
        txt_harga.setRoundedkiriatas(15);
        txt_harga.setRoundedkiribawah(15);
        roundednew3.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 200, 50));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(90, 142, 149));
        jLabel3.setText("Harga Produk");
        roundednew3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 31));

        button1.setBackground(new java.awt.Color(229, 225, 218));
        button1.setText("KONFIMASI");
        button1.setFont(new java.awt.Font("Poppins", 1, 25)); // NOI18N
        button1.setRadius(15);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        roundednew3.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 490, 50));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(90, 142, 149));
        jLabel2.setText("Tambah Produk");
        roundednew3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 31));

        txt_name2.setBackground(new java.awt.Color(242, 242, 242));
        txt_name2.setBorder(null);
        txt_name2.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_name2.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        txt_name2.setRoundedkananatas(15);
        txt_name2.setRoundedkananbawah(15);
        txt_name2.setRoundedkiriatas(15);
        txt_name2.setRoundedkiribawah(15);
        roundednew3.add(txt_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 490, 50));

        txt_harga1.setBackground(new java.awt.Color(242, 242, 242));
        txt_harga1.setBorder(null);
        txt_harga1.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_harga1.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        txt_harga1.setRoundedkananatas(15);
        txt_harga1.setRoundedkananbawah(15);
        txt_harga1.setRoundedkiriatas(15);
        txt_harga1.setRoundedkiribawah(15);
        roundednew3.add(txt_harga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 260, 50));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(90, 142, 149));
        jLabel8.setText("Harga Produk");
        roundednew3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, 31));

        add(roundednew3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 550, 380));

        roundednew4.setColorend(new java.awt.Color(170, 215, 217));
        roundednew4.setColorstar(new java.awt.Color(170, 215, 217));
        roundednew4.setRoundedkananatas(50);
        roundednew4.setRoundedkananbawah(50);
        roundednew4.setRoundedkiriatas(50);
        roundednew4.setRoundedkiribawah(50);
        roundednew4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button2.setText("button2");
        button2.setRadius(30);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        roundednew4.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 39, 150, 225));

        Hapus.setRadius(30);
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        roundednew4.add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 39, 150, 225));

        Update.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        Update.setRadius(30);
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        roundednew4.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 39, 150, 225));

        add(roundednew4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 550, 300));

        roundednew5.setColorend(new java.awt.Color(170, 215, 217));
        roundednew5.setColorstar(new java.awt.Color(170, 215, 217));
        roundednew5.setRoundedkananatas(50);
        roundednew5.setRoundedkananbawah(50);
        roundednew5.setRoundedkiriatas(50);
        roundednew5.setRoundedkiribawah(50);
        roundednew5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(90, 142, 149));
        jLabel1.setText("Tambah Produk");
        roundednew5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, 31));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(90, 142, 149));
        jLabel4.setText("Tambah Produk");
        roundednew5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, 31));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(90, 142, 149));
        jLabel5.setText("Tambah Produk");
        roundednew5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, 31));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(90, 142, 149));
        jLabel6.setText("Tambah Produk");
        roundednew5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, 31));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(90, 142, 149));
        jLabel7.setText("Tambah Produk");
        roundednew5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, 31));

        txt_name1.setBackground(new java.awt.Color(242, 242, 242));
        txt_name1.setBorder(null);
        txt_name1.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_name1.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        txt_name1.setInheritsPopupMenu(true);
        txt_name1.setRoundedkananatas(15);
        txt_name1.setRoundedkananbawah(15);
        txt_name1.setRoundedkiriatas(15);
        txt_name1.setRoundedkiribawah(15);
        roundednew5.add(txt_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 395, 200, 40));

        txt_name3.setBackground(new java.awt.Color(242, 242, 242));
        txt_name3.setBorder(null);
        txt_name3.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_name3.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        txt_name3.setInheritsPopupMenu(true);
        txt_name3.setRoundedkananatas(15);
        txt_name3.setRoundedkananbawah(15);
        txt_name3.setRoundedkiriatas(15);
        txt_name3.setRoundedkiribawah(15);
        roundednew5.add(txt_name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 455, 200, 40));

        txt_name4.setBackground(new java.awt.Color(242, 242, 242));
        txt_name4.setBorder(null);
        txt_name4.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_name4.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        txt_name4.setInheritsPopupMenu(true);
        txt_name4.setRoundedkananatas(15);
        txt_name4.setRoundedkananbawah(15);
        txt_name4.setRoundedkiriatas(15);
        txt_name4.setRoundedkiribawah(15);
        roundednew5.add(txt_name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 575, 200, 40));

        txt_name5.setBackground(new java.awt.Color(242, 242, 242));
        txt_name5.setBorder(null);
        txt_name5.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_name5.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        txt_name5.setInheritsPopupMenu(true);
        txt_name5.setRoundedkananatas(15);
        txt_name5.setRoundedkananbawah(15);
        txt_name5.setRoundedkiriatas(15);
        txt_name5.setRoundedkiribawah(15);
        roundednew5.add(txt_name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 515, 200, 40));

        txt_name6.setBackground(new java.awt.Color(242, 242, 242));
        txt_name6.setBorder(null);
        txt_name6.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_name6.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        txt_name6.setInheritsPopupMenu(true);
        txt_name6.setRoundedkananatas(15);
        txt_name6.setRoundedkananbawah(15);
        txt_name6.setRoundedkiriatas(15);
        txt_name6.setRoundedkiribawah(15);
        roundednew5.add(txt_name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 635, 200, 40));

        add(roundednew5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 560, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
  
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
   
    }//GEN-LAST:event_HapusActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
       
    }//GEN-LAST:event_UpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Aset.button Hapus;
    private Aset.button Update;
    private Aset.button button1;
    private Aset.button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel judul;
    private Aset.roundednew roundednew3;
    private Aset.roundednew roundednew4;
    private Aset.roundednew roundednew5;
    private Aset.RoundedTextField txt_harga;
    private Aset.RoundedTextField txt_harga1;
    private Aset.RoundedTextField txt_name1;
    private Aset.RoundedTextField txt_name2;
    private Aset.RoundedTextField txt_name3;
    private Aset.RoundedTextField txt_name4;
    private Aset.RoundedTextField txt_name5;
    private Aset.RoundedTextField txt_name6;
    // End of variables declaration//GEN-END:variables
}
