/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Kasir_Produk;

import Aset.roundednew;
import ServiceReport.CetakNota;
import com.formdev.flatlaf.FlatClientProperties;
import javax.swing.JOptionPane;

/**
 *
 * @author achmad ifan
 */
public class Nota extends roundednew {

    
    public Nota() {
        initComponents();
        viewNota();
        
    }
    
    String id_pelanggan = "";
    
    
    private void ambilIdPelanggan() {
    String nilai = DataManager.getInstance().getNilai();
    id_pelanggan = nilai;
    }
    
    private final CetakNota servis = new Kasir.DAO.Nota();
    
//    private void setLayOutForm(){
//        roundednew1.putClientProperty(FlatClientProperties.STYLE, ""
//    + "background:$Produk.background");
//
//txtPencarian.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Pencarian"); 
//    }
        
    
    private void viewNota(){
        viewNota.removeAll();
        ambilIdPelanggan();
        servis.cetakNota(viewNota, id_pelanggan);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundednew1 = new Aset.roundednew();
        viewNota = new Aset.roundednew();

        setRoundedkananatas(20);
        setRoundedkananbawah(20);
        setRoundedkiriatas(20);
        setRoundedkiribawah(20);

        roundednew1.setColorend(new java.awt.Color(242, 242, 242));
        roundednew1.setColorstar(new java.awt.Color(242, 242, 242));
        roundednew1.setRoundedkananatas(20);
        roundednew1.setRoundedkananbawah(20);
        roundednew1.setRoundedkiriatas(20);
        roundednew1.setRoundedkiribawah(20);
        roundednew1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewNota.setColorend(new java.awt.Color(204, 204, 204));
        viewNota.setColorstar(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout viewNotaLayout = new javax.swing.GroupLayout(viewNota);
        viewNota.setLayout(viewNotaLayout);
        viewNotaLayout.setHorizontalGroup(
            viewNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        viewNotaLayout.setVerticalGroup(
            viewNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        roundednew1.add(viewNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 350, 496));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundednew1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundednew1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Aset.roundednew roundednew1;
    private Aset.roundednew viewNota;
    // End of variables declaration//GEN-END:variables
}
