/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Kasir_Produk;

import Aset.roundednew;
import Aset.button;
import Koneksi.Koneksi;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

 
 
public class Transaksi extends javax.swing.JPanel {

    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
        tampildata();
    }
    public void tampildata() {
        Connection conn;
PreparedStatement pst;
ResultSet rs;

if (tgl_awal.getDate() == null || tgl_akhir.getDate() == null) {
    JOptionPane.showMessageDialog(null, "Silakan pilih tanggal awal dan tanggal akhir terlebih dahulu!");
    return; // Hentikan eksekusi selanjutnya
}
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
String tglAwalStr = sdf.format(tgl_awal.getDate());
String tglAkhirStr = sdf.format(tgl_akhir.getDate());

String sql = "SELECT Tanggal_Pesanan, Nama_Pelanggan, Nama_Produk, Jumlah_Pesanan, Total_Harga, Status FROM pesanan JOIN produk ON pesanan.Id_Produk = produk.Id_Produk JOIN detail_pesanan ON detail_pesanan.Id_Pesanan = pesanan.Id_Pesanan JOIN pelanggan ON detail_pesanan.Id_Pelanggan = pelanggan.Id_Pelanggan  WHERE Tanggal_Pesanan BETWEEN ? AND ? ORDER BY Tanggal_Pesanan ASC";
try {
    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/kasir_v2", "root", "");
    pst = conn.prepareStatement(sql);
    pst.setString(1, tglAwalStr);
    pst.setString(2, tglAkhirStr);
    rs = pst.executeQuery();

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Tanggal_Pesanan");
    model.addColumn("Nama_Pelanggan");
    model.addColumn("Nama_Produk");
    model.addColumn("Jumlah_Pesanan");
    model.addColumn("Total_Harga");
    model.addColumn("Status");
    
    while (rs.next()) {
        model.addRow(new Object[] {
            rs.getString("Tanggal_Pesanan"),
            rs.getString("Nama_Pelanggan"),
            rs.getString("Nama_Produk"),
            rs.getString("Jumlah_Pesanan"),
            rs.getString("Total_Harga"),
            rs.getString("Status")
        });
    }

    table1.setModel(model);

} catch (SQLException e) {
    e.printStackTrace();
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundednew2 = new Aset.roundednew();
        roundednew1 = new Aset.roundednew();
        konfir = new Aset.button();
        judul14 = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        judul16 = new javax.swing.JLabel();
        judul13 = new javax.swing.JLabel();
        tgl_awal = new com.toedter.calendar.JDateChooser();
        tgl_akhir = new com.toedter.calendar.JDateChooser();
        roundednew3 = new Aset.roundednew();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new Aset.JTableRounded();
        roundednew6 = new Aset.roundednew();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        roundednew2.setColorend(new java.awt.Color(242, 242, 242));
        roundednew2.setColorstar(new java.awt.Color(242, 242, 242));
        roundednew2.setRoundedkananatas(50);
        roundednew2.setRoundedkananbawah(50);
        roundednew2.setRoundedkiriatas(50);
        roundednew2.setRoundedkiribawah(50);

        roundednew1.setBackground(new java.awt.Color(251, 249, 241));
        roundednew1.setForeground(new java.awt.Color(251, 249, 241));
        roundednew1.setColorend(new java.awt.Color(170, 215, 217));
        roundednew1.setColorstar(new java.awt.Color(170, 215, 217));
        roundednew1.setPreferredSize(new java.awt.Dimension(520, 340));
        roundednew1.setRoundedkananatas(50);
        roundednew1.setRoundedkananbawah(50);
        roundednew1.setRoundedkiriatas(50);
        roundednew1.setRoundedkiribawah(50);

        konfir.setBackground(new java.awt.Color(229, 225, 218));
        konfir.setForeground(new java.awt.Color(90, 142, 149));
        konfir.setText("KONFIRMASI");
        konfir.setColor(new java.awt.Color(229, 225, 218));
        konfir.setColorborder(new java.awt.Color(229, 225, 218));
        konfir.setColorclic(new java.awt.Color(229, 225, 218));
        konfir.setColorover(new java.awt.Color(229, 225, 218));
        konfir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        konfir.setRadius(15);
        konfir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirActionPerformed(evt);
            }
        });

        judul14.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        judul14.setForeground(new java.awt.Color(255, 255, 255));
        judul14.setText("Tanggal Awal");

        judul1.setFont(new java.awt.Font("Poppins", 1, 30)); // NOI18N
        judul1.setForeground(new java.awt.Color(255, 255, 255));
        judul1.setText("Filter");

        judul16.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        judul16.setForeground(new java.awt.Color(255, 255, 255));
        judul16.setText("Tanggal Akhir");

        judul13.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        judul13.setForeground(new java.awt.Color(255, 255, 255));
        judul13.setText("Mencari Sesuai Nama Pelanggan   ?");

        javax.swing.GroupLayout roundednew1Layout = new javax.swing.GroupLayout(roundednew1);
        roundednew1.setLayout(roundednew1Layout);
        roundednew1Layout.setHorizontalGroup(
            roundednew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundednew1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(roundednew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundednew1Layout.createSequentialGroup()
                        .addComponent(konfir, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(roundednew1Layout.createSequentialGroup()
                        .addGroup(roundednew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judul14, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_awal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(roundednew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judul16, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))))
            .addGroup(roundednew1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundednew1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judul13)
                .addGap(103, 103, 103))
        );
        roundednew1Layout.setVerticalGroup(
            roundednew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundednew1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(roundednew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judul14)
                    .addComponent(judul16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundednew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundednew1Layout.createSequentialGroup()
                        .addComponent(tgl_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(konfir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(judul13))
                    .addComponent(tgl_awal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        roundednew3.setBackground(new java.awt.Color(251, 249, 241));
        roundednew3.setForeground(new java.awt.Color(251, 249, 241));
        roundednew3.setColorend(new java.awt.Color(170, 215, 217));
        roundednew3.setColorstar(new java.awt.Color(170, 215, 217));
        roundednew3.setPreferredSize(new java.awt.Dimension(520, 340));
        roundednew3.setRoundedkananatas(50);
        roundednew3.setRoundedkananbawah(50);
        roundednew3.setRoundedkiriatas(50);
        roundednew3.setRoundedkiribawah(50);

        table1.setBackground(new java.awt.Color(204, 204, 204));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "Nama Pelanggan", "Produk", "Jumlah", "Harga", "Status"
            }
        ));
        table1.setRoundedkananatas(50);
        table1.setRoundedkananbawah(50);
        table1.setRoundedkiriatas(50);
        table1.setRoundedkiribawah(50);
        jScrollPane1.setViewportView(table1);

        javax.swing.GroupLayout roundednew3Layout = new javax.swing.GroupLayout(roundednew3);
        roundednew3.setLayout(roundednew3Layout);
        roundednew3Layout.setHorizontalGroup(
            roundednew3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundednew3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        roundednew3Layout.setVerticalGroup(
            roundednew3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundednew3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        roundednew6.setBackground(new java.awt.Color(251, 249, 241));
        roundednew6.setForeground(new java.awt.Color(251, 249, 241));
        roundednew6.setColorend(new java.awt.Color(170, 215, 217));
        roundednew6.setColorstar(new java.awt.Color(170, 215, 217));
        roundednew6.setPreferredSize(new java.awt.Dimension(520, 340));
        roundednew6.setRoundedkananatas(50);
        roundednew6.setRoundedkananbawah(50);
        roundednew6.setRoundedkiriatas(50);
        roundednew6.setRoundedkiribawah(50);

        jLabel1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 63, 65));
        jLabel1.setText("%");

        jLabel2.setFont(new java.awt.Font("Poppins ExtraBold", 0, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(60, 63, 65));
        jLabel2.setText("0");

        javax.swing.GroupLayout roundednew6Layout = new javax.swing.GroupLayout(roundednew6);
        roundednew6.setLayout(roundednew6Layout);
        roundednew6Layout.setHorizontalGroup(
            roundednew6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundednew6Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        roundednew6Layout.setVerticalGroup(
            roundednew6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundednew6Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(roundednew6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roundednew2Layout = new javax.swing.GroupLayout(roundednew2);
        roundednew2.setLayout(roundednew2Layout);
        roundednew2Layout.setHorizontalGroup(
            roundednew2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundednew2Layout.createSequentialGroup()
                .addGroup(roundednew2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundednew2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(roundednew1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roundednew6, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundednew2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(roundednew3, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundednew2Layout.setVerticalGroup(
            roundednew2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundednew2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundednew2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundednew1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundednew6, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundednew3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundednew2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundednew2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void konfirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirActionPerformed
       tampildata();
        // TODO add your handling code here:
    }//GEN-LAST:event_konfirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul13;
    private javax.swing.JLabel judul14;
    private javax.swing.JLabel judul16;
    private Aset.button konfir;
    private Aset.roundednew roundednew1;
    private Aset.roundednew roundednew2;
    private Aset.roundednew roundednew3;
    private Aset.roundednew roundednew6;
    private Aset.JTableRounded table1;
    private com.toedter.calendar.JDateChooser tgl_akhir;
    private com.toedter.calendar.JDateChooser tgl_awal;
    // End of variables declaration//GEN-END:variables
}
